### ISSUE TITLE
Newest nightly - qView asks for permission to open file every-time from Downloads, Desktop and Documents Folder.

### ISSUE THREAD

**Issue by LampPrinter** [jurplel/qView#542] opened 2022-12-23 01:28 UTC
qView-nightly-2022-12-18.1
MaOS Ventura 13.1

Like the heading says. If a file is opened from ~Downloads, ~Desktop or ~Documents folder qView will ask for permission every-time. Despite granting it permission last time around.

**Comment by LampPrinter** [comment] 2022-12-25 06:07
@jdpurcell 
Latest nightly on your repo fixes the permission issue but zoom is messed up now. Please see the attached photo. All default settings.

<img width="928" alt="iShot_2022-12-25_11 33 49" src="https://user-images.githubusercontent.com/7559328/209458546-ee673e5f-a0b6-406c-a538-3ef9803fa667.png">

**Comment by jdpurcell** [comment] 2022-12-25 06:28
@LampPrinter Oops! Yeah I rewrote a fair portion of the zoom/positioning logic recently, I must have missed something. I can indeed reproduce some weird issues like that with the default settings, I think it's mostly because I usually have "Image scaling" off that I missed it. If you turn that off it'll probably work, and I'll see about fixing it tomorrow.

**Comment by LampPrinter** [comment] 2022-12-25 06:48
@jdpurcell yes, turning off "Image scaling" fixed the issue.
The only other bug I can notice now is that it does not remember the recently opened files after quitting the app.

**Comment by jdpurcell** [comment] 2022-12-25 19:11
@LampPrinter I believe the positioning/zoom(?) issue with default settings is fixed now.

As for not remembering recent files, I have no idea unfortunately. It's working fine for me and I can't think of any code changes I made that would affect that.

**Closed** 2022-12-26 20:32 UTC
Labels: bug
