### ISSUE TITLE
Need to be able to specify what file extensions it will try to open

### ISSUE THREAD

**Issue by cretace** [jurplel/qView#638] opened 2023-09-28 18:05 UTC
Windows 10
When viewing images using arrows to scroll through a directory, when it hits a PSD file it tries to open it and then gives an error.
I should be able to specify that it never attempts to view PSDs

**Comment by BloodRaven0** [comment] 2023-11-15 13:39
+1 I have the same problem. My work includes going through folders full of jpeg images, each of which has a .psd version in the same folder, and some are 500mb or more, so browsing through these directories with the arrow keys is impossible.
Please let us disable the PSD file format!

**Comment by jdpurcell** [comment] 2023-11-24 17:20
Duplicate of #603

**Closed** 2023-11-28 03:55 UTC
Labels: bug, duplicate
