### ISSUE TITLE
"._" prefixed files on macos should be ignored, currently cause "error 4")

### ISSUE THREAD

**Issue by sandrosem** [jurplel/qView#676] opened 2024-04-24 10:17 UTC
Hi!

Love the app! 

There's just one small but annoying issue on macos: 
qview also tries to display the hidden "._" files that macos (I'm on sonoma) creates (for indexing purposes, I believe) of every file, e.g. "._image.jpg" from "image.jpg" which then causes error 4 to pop up, thus interrupting the slideshow. If you could add a function (or option) to ignore everything that starts with "._" or is a hidden file, that would be awesome!

Thx!

EDIT: for some reason github automatically changes the last mention of the prefix into a simple dot. I mean of course "dot underscore".

**Comment by jdpurcell** [comment] 2024-04-24 23:34
Duplicate of #651 which was already fixed in the master branch but not released yet. There are "nightly" builds from GitHub Actions, although the last one from the master branch was so long ago that the download links have expired. But you could grab one from [here](https://github.com/jurplel/qView/actions/runs/8824416948) which is associated with one of my pull requests (disclaimer: changes not yet reviewed/approved by @jurplel), and includes the enhancement to skip dot-underscore files.

**Comment by jurplel** [comment] 2024-05-02 13:34
> Duplicate of #651 which was already fixed in the master branch but not released yet. There are "nightly" builds from GitHub Actions, although the last one from the master branch was so long ago that the download links have expired. But you could grab one from [here](https://github.com/jurplel/qView/actions/runs/8824416948) which is associated with one of my pull requests (disclaimer: changes not yet reviewed/approved by @jurplel), and includes the enhancement to skip dot-underscore files.

I ran the action again manually so you should have a new download link for now

**Comment by jurplel** [comment] 2024-06-25 06:29
should be resolved? closing

**Closed by jurplel** 2024-06-25 06:29 UTC
Labels: bug
