### ISSUE TITLE
Images blur on zoom

### ISSUE THREAD

**Issue by timea-techgirl** [jurplel/qView#407] opened 2021-03-07 20:25 UTC
**Environment:**
- OS: Windows 10 x64
- qView version: 4.0

**Information:**
HEIC images are too blurred on zoom. Normal images are slightly blurred.
Zoom an image and it is slighty blurred. Here is a comparison with another image viewer app.

![image](https://user-images.githubusercontent.com/7058205/110253537-e8b3c800-7fb0-11eb-81da-4bcaa350aeb5.png)

**Comment by jurplel** [comment] 2021-03-07 20:46
Try turning off bilinear filtering in the options and see if that is more the result you are looking for

**Comment by timea-techgirl** [comment] 2021-03-07 20:56
> Try turning off bilinear filtering in the options and see if that is more the result you are looking for

Thanks, I had to disable Image scaling along with Bilinear filtering to fix it.  Now HEIC images appear clear too but takes 4 to 5 seconds to load each image.

**Comment by jurplel** [comment] 2021-03-07 21:14
Interesting, thank you for the info. The HEIC plugin is a bit slow and I am planning to switch to a newer one next version.

Image scaling has a serious issue that may be related: https://github.com/jurplel/qView/issues/259

There is a feature request to disable bilinear filtering at high zoom percentages, which would prevent this as well: https://github.com/jurplel/qView/issues/356

**Comment by jurplel** [comment] 2023-05-01 19:21
closing since it's old, feel free to reopen if you can still reproduce

**Closed by jurplel** 2023-05-01 19:21 UTC
Labels: bug
