### ISSUE TITLE
Retain zoom level on file change

### ISSUE THREAD

**Issue by eugenesvk** [jurplel/qView#452] opened 2021-09-23 05:08 UTC
Currently qView helpfully retains the **orientation** (flip, mirror, rotate left/right) of an image on switching files, which is great when you have a batch of files with the same wrong rotation.

However, the **zoom level is reset** each time, which is **bad** for e.g. you're trying to compare quality of different images at high zoom levels — switching back&forth is the best method, but you can't do it when zoom is reset

Would you please add a configuration where I could make the zoom level **stick?**
Ideally that's something that should be configurable via a shortcut so I can turn it on/off easily whenever needed since it really depends on your workflow

**Comment by jurplel** [comment] 2021-09-24 20:23
Actually, a duplicate of https://github.com/jurplel/qView/issues/70 from way back. I agree, should be done at some point.

**Closed by jurplel** 2021-09-24 20:23 UTC
Labels: enhancement
