### ISSUE TITLE
unable to open JPEG XL

### ISSUE THREAD

**Issue by superbonaci** [jurplel/qView#535] opened 2022-12-15 20:32 UTC
Unable to open jxl:

[animation-woods.jxl.zip](https://github.com/jurplel/qView/files/10240437/animation-woods.jxl.zip)

**Comment by jurplel** [comment] 2022-12-21 13:55
what OS? what version? how did you download it?

**Comment by superbonaci** [comment] 2022-12-24 11:18
Installed for macOS with brew (using Apple M2)
https://formulae.brew.sh/cask/qview

**Comment by jurplel** [comment] 2023-01-11 16:32
possibly a distribution issue. Putting the plugins in for qview 5.0 was just done manually since it is annoying to automate

**Comment by jurplel** [comment] 2023-01-11 21:21
Duplicate of #485

**Closed by jurplel** 2023-01-11 21:21 UTC
Labels: bug
