### ISSUE TITLE
Support for multi-page TIFF

### ISSUE THREAD

**Issue by linwe9** [jurplel/qView#357] opened 2020-10-04 19:22 UTC
I'm a graphic designer, so sometimes i have to work with multi-page TIFF files.
While Apple Preview app can do the job, i'd rather do it with the sheer minimalism and easy browsing capabilities of qView.
Hopefully this feature can be added for next versions.

Thanks in advance.

**Comment by jurplel** [comment] 2020-10-04 23:16
Kinda already planned with https://github.com/jurplel/qView/issues/305 but I'll have to see if TIFFs are possible when implementing that.

**Comment by NicTanghe** [comment] 2023-03-01 10:52
Hello what  is the status with tiff support ?

**Comment by jurplel** [comment] 2023-05-01 17:52
This requires implementing a new internal paradigm for handling files with multiple page types. It is non-trivial to do this at the moment, and there are higher priority things to work on.

Closing this issue because it is, in effect, a duplicate of #305.

**Closed by jurplel** 2023-05-01 17:52 UTC
Labels: enhancement
