### ISSUE TITLE
SVG file not displayed properly

### ISSUE THREAD

**Issue by VarinderMick** [jurplel/qView#554] opened 2023-01-08 06:30 UTC
**Environment:**
- OS: [Windows ]
- qView version: [3.0 to 5.0]

**Information:**
The SVG file is not displayed properly (Done.svg) as it opened in browsers.
also I get error while opening drawing.svg : Error 3: Unsupported image format
or it shows Fonts not in actual scale.

![error](https://user-images.githubusercontent.com/122196218/211183464-2a942ed2-ea36-48f1-a281-798c72af7b37.jpg)
![Open in firefox](https://user-images.githubusercontent.com/122196218/211183587-7d558cf3-187e-4c0f-aac3-d9370f8cd81c.jpg)
![open in qview](https://user-images.githubusercontent.com/122196218/211183589-e835cb04-6614-405e-8740-60b8b12c1ccf.jpg)
![Done](https://user-images.githubusercontent.com/122196218/211183620-7922017d-e6ff-4a10-910c-86b114a6945a.svg)
![drawing](https://user-images.githubusercontent.com/122196218/211183621-ec677cd9-992b-4ef3-b46f-fa70e23f638e.svg)

**Comment by jurplel** [comment] 2023-01-11 16:35
Only have a Linux computer with me right now, but FWIW I cannot reproduce it on this machine.

Will try with Windows when I get a chance

**Comment by missdeer** [comment] 2023-08-04 06:51
It's ok with the latest commit built with Qt 6.5.1 on my Windows 10 machine.

**Comment by jurplel** [comment] 2023-08-04 16:23
In that case i'll close the issue

**Closed by jurplel** 2023-08-04 16:23 UTC
Labels: support
