### ISSUE TITLE
AVIF with HDR color space

### ISSUE THREAD

**Issue by lonely701** [jurplel/qView#541] opened 2022-12-22 01:55 UTC
OS: Windows 10 22H2
qView version: 5.15.2 (x86_64)

The website I found
https://people.csail.mit.edu/ericchan/hdr/hdr.php

It contains HDR AVIF images, which qView is able to open but the color is not correct, no matter if the HDR is turned on in Windows Display settings. No matter if the display support HDR. At the same time, Chrome 109.0.5414.46 beta always displays in full dynamic range.

**Comment by jurplel** [comment] 2023-01-11 16:33
Duplicate of #214

**Closed by jurplel** 2023-01-11 16:33 UTC
Labels: enhancement
