### ISSUE TITLE
TIF image looks slightly desaturated in qView

### ISSUE THREAD

**Issue by ruffianlabs** [jurplel/qView#506] opened 2022-09-01 02:09 UTC
**Environment:**
- Windows 10
- qView 5.0

**Information:**
I tried to open this TIF image in qView 
> Full Res (For Print), 14575 X 8441, TIF (129.33 MB)

from [Cosmic Cliffs by JWST](https://webbtelescope.org/contents/media/images/2022/031/01G77PKB8NKR7S8Z6HBXMYATGJ) but, it displays as a slightly desaturated image. 

Check the same image opened in **Windows Photo Viewer & qView** in this screenshot:
![Shot 010922 073638AM](https://user-images.githubusercontent.com/112596796/187816947-637e4359-63ac-4872-9e6e-066f02c13fd1.jpg)

To reproduce, Please download & View that TIF image in qView.

**Comment by jurplel** [comment] 2022-09-04 15:21
Does the issue still present if you switch your PC to use the srgb color space?

**Comment by jdpurcell** [comment] 2022-12-04 20:44
Duplicate of #283. Tested with #521, and the color space conversion option fixes it.

**Closed as completed** 2023-05-01 18:58 UTC
Labels: bug
