### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by terraner** [jurplel/qView#435] opened 2021-06-25 12:22 UTC
Hi,
I'd like to see the option, to view EXIF data from inside qView by simply pressing a key (i.e. e) or extending the information shown after pressing 'i'

**Comment by jurplel** [comment] 2021-06-25 22:56
Duplicate of https://github.com/jurplel/qView/issues/94

**Comment by jurplel** [comment] 2021-06-25 22:56
Thanks for the suggestion!

**Closed by jurplel** 2021-06-25 22:56 UTC
