### ISSUE TITLE
.cbz Support

### ISSUE THREAD

**Issue by tocotronaut** [jurplel/qView#433] opened 2021-06-21 14:49 UTC
would be nice to have CBZ / CBR Support in Qview.

cbr are only zipped (or Rar'ed) Jpegs.

**Comment by jurplel** [comment] 2021-06-24 02:15
Would likely require automatic decompression (cbr, cba, cbg, and cbb would be supported too i guess)

**Comment by jurplel** [comment] 2023-05-01 19:34
actually, weirdly duplicate of the ancient #64

**Closed by jurplel** 2023-05-01 19:34 UTC
Labels: enhancement
