### ISSUE TITLE
Allow directly erasing files

### ISSUE THREAD

**Issue by es20490446e** [jurplel/qView#520] opened 2022-10-31 17:44 UTC
When watching an image, if you press the delete key, it gets moved to the trash.

The problem is that some systems don't make use of the trash, and they even have it removed from eyesight. So people have images moved to the trash, and not noticing they stay there forever.

So it could be nice having an option to just erase the image straight away.

**Comment by jurplel** [comment] 2023-05-01 18:49
I agree! Duplicate of #520.

**Closed by jurplel** 2023-05-01 18:49 UTC
Labels: enhancement

**Comment by es20490446e** [comment] 2023-05-01 19:08
@jurplel Reopen. You made the bug duplicate of itself!

**Comment by jurplel** [comment] 2023-05-01 19:23
Lol

I meant, duplicate of #497

**Comment by es20490446e** [comment] 2023-05-01 19:35
Jajaja 😛
