### ISSUE TITLE
unable to open animated svg X (twitter)

### ISSUE THREAD

**Issue by 3xploiton3** [jurplel/qView#642] opened 2023-10-12 00:43 UTC
**Environment:**
- OS: Windows 11
- qView version: [6.1]

**Information:**
![image](https://github.com/jurplel/qView/assets/19517680/f7659a10-5b83-4605-9767-62d048ad82a7)

Sample File
https://www.dropbox.com/scl/fi/dcmenunj9knu5fk6eh7vb/twitter-x-alt.svg?rlkey=01j4q7yvyqbzy5af5nn0ojuur&dl=0

**Comment by jurplel** [comment] 2024-06-25 06:29
This is a duplicate of #681 I believe

**Closed by jurplel** 2024-06-25 06:29 UTC
Labels: bug
