### ISSUE TITLE
Display P3 color profile not respected with any PNG image

### ISSUE THREAD

**Issue by ghost** [jurplel/qView#614] opened 2023-08-12 18:42 UTC
**Environment:**
- OS: macOS 13.5 Ventura
- qView version: nightly 2023-08-12.1

**Information:**
This is _**not**_ the same issue as #606.

Display P3 color profile is not respected with **_any_** PNG image. For example, when you download [this PNG image](https://workupload.com/file/s8j8hVJcAJG) and open it in qView, the colors will be too pale. Apples Preview.app and other color-management capable viewers display the same PNG file with correct colors.

This error does not occur with qView-nightly-macOS-2023-05-13.2. So, the error must have been introduced between 2023-05-13 and 2023-08-12.

**Comment by jdpurcell** [comment] 2023-08-12 19:47
Did some testing, can also reproduce with the attached image. It seems that Qt's built-in PNG decoder is fine, but after the additional image format plugins were added, QtApng now takes over normal PNG decoding and perhaps it doesn't support reporting color space information.

![Webkit-logo-P3](https://github.com/jurplel/qView/assets/6741660/f982bced-2306-451b-a6d6-73dee5040247)

**Comment by jdpurcell** [comment] 2023-08-12 22:30
I saw a note in QtApng's readme: _Since the png format is already used by Qt, *.png files will not use the plugin. To load a png as animated, you can either rename the file to *.apng, or set the format explicitly_

So I thought something in qView's movie detection was forcing it to use QtApng, but even after commenting out the relevant parts (https://github.com/jdpurcell/qView/commit/2b0cead0de0695a350b0e6f40ec0a7d9b8afc56f and https://github.com/jdpurcell/qView/commit/d407038a3b916e743f64c04fc6f4b9d774aacd27), it really does seem QtApng is taking over all PNG decoding.

**Comment by jurplel** [comment] 2023-08-13 20:23
Should be fixed in the latest build thanks to @jdpurcell's investigation. will ship in 6.1

**Closed as completed** 2023-08-13 20:37 UTC
Labels: bug
