### ISSUE TITLE
Dragging a folder onto qView results in a File not found error on macOS

### ISSUE THREAD

**Issue by zakx** [jurplel/qView#479] opened 2022-01-21 10:21 UTC
**Environment:**
- OS: macOS 12.1 (Intel)
- qView version: 5.0

**Information:**

Drag a folder containing images and drop it on the main app window and a "File not found" error dialog appears.

![Screenshot 2022-01-21 at 11 18 56](https://user-images.githubusercontent.com/628602/150510125-3e5d7ce4-3f0a-43ed-8a50-890f07d56dbf.png)

I would expect qView to instead open the folder and display the first image (based on the ordering that was set up).

**Comment by jurplel** [comment] 2022-01-21 14:04
The issue is there is no mechanism for qVIew to open a folder. It only knows how to open files. This would be a nice behavior to add.

> If you choose to fix this (thanks!), please also enable dropping folders onto the app icon in the Dock. It works for images but does not accept folders.

Probably both of them will be fixed at once if/when I fix this

**Comment by fredcallaway** [comment] 2022-03-03 15:11
I might be misunderstanding, but it seems like qView is intended to support browsing through images in a directory (e.g., on under "New Features" on the website, we have "Reaching an invalid image now allows you to keep moving through the current folder with the arrow keys". And there is the existence of the "Go" menu (with entries like "Next File")

Is there some other way to open a folder? Is this feature just missing on Mac at the moment?

**Closed** 2023-01-11 20:54 UTC
Labels: bug

**Comment by fredcallaway** [comment] 2023-01-11 23:33
Does this mean opening a folder is implemented? It's not working with the current release (5.0) for me.

**Comment by jdpurcell** [comment] 2023-01-11 23:56
@fredcallaway qView already supported browsing through images in a folder - once you are viewing an image, press the left or right arrow on your keyboard to navigate to neighboring files within the folder. The only thing added recently (for a future release; not present in qView 5.0) was the ability to drop a folder onto qView, which is just a convenient way of opening the first file in the folder.

**Comment by fredcallaway** [comment] 2023-01-12 00:00
Got it. That is the feature I was hoping for. Is there an easy way to download a bleeding edge version (not building from source)?

**Comment by jdpurcell** [comment] 2023-01-12 00:13
@fredcallaway Yes! On the main qView GitHub page you can click the green check mark next to the latest commit and then click any of the Details links.
![image](https://user-images.githubusercontent.com/6741660/211944585-b9613948-4277-4d4f-af6a-6f647c6d74a2.png)

Then click on Summary.
![image](https://user-images.githubusercontent.com/6741660/211944710-0bcef465-fcb0-4a33-b076-3dbb5cce8946.png)

And scroll to the bottom to find the build artifacts:
![image](https://user-images.githubusercontent.com/6741660/211944961-b8299cdf-4057-475c-a8d2-afe2b32b80d2.png)

If you are signed into GitHub, each artifact is a clickable link to download the .zip of the binaries.

**Comment by fredcallaway** [comment] 2023-01-15 15:44
Much thanks @jdpurcell! It's working great (including `open -a 'qView' path` on the command line, macos).
