### ISSUE TITLE
Feature: transparent background

### ISSUE THREAD

**Issue by cangSDARM** [jurplel/qView#628] opened 2023-09-01 12:31 UTC
## Expectation
see screenshot

## For Windows

those api should do this work: 

- https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setlayeredwindowattributes
- https://learn.microsoft.com/en-us/windows/win32/devnotes/wm-ctlcolor-

### steps: 

1. Use layered window;
2. background(layer) uses `SetLayeredWindowAttributes` to set the alpha channel;
3. foreground(the layer that renders the image) uses `WM_CTLCOLOR` to set the area in which the background(layer) is presented to transparent.

### guides(Chinese, consider use the web translator)

- https://blog.51cto.com/johns/165953
- https://bbs.huaweicloud.com/blogs/383902

## For other platforms
sry, I don't know :)

## Screenshot/Result
![image](https://github.com/jurplel/qView/assets/20441896/4f505522-b54f-4795-83f4-30754967d185)

**Comment by Matherone** [comment] 2023-12-04 11:23
Yes, transparent backgrounds are fun. They can also be quite useful. 

User scenario: When used in conjuction with multiple borderless qView instances, it is super easy to make e.g. quick-and-dirty mockups and image collages. Just double-click a few images in an OS folder, resize and position them on screen. Repeat and screenshot when done.  

If memory serves, the old minimalistic image viewer [stb_imv](https://github.com/nothings/stb-imv) worked a bit like this.

Never underestimate the power of fun.

**Comment by r3538987** [comment] 2024-01-03 16:10
This is also how Google's Picasa open images by default. Simple image without any HUD elements shown, background is transparent and slightly darker.

**Comment by jurplel** [comment] 2024-01-12 22:05
This is a duplicate of https://github.com/jurplel/qView/issues/258

This does present a lot of UX challenges, such as how to move the window/work around the window manager not providing decorations on some platforms. It might require a lot of platform-specific code. It might also require an additional logical "mode" if we wanted to have a "quick look" sort of functionality like macOS but switch to the regular interface when you click or something of that sort.

In essence, this is actually a pretty large project

**Closed by jurplel** 2024-01-12 22:05 UTC
Labels: enhancement

**Comment by r3538987** [comment] 2025-10-23 18:56
@jurplel In case if we aren't getting Picasa look, is there a chance to hide title bar? 
Where we have simple bordered viewport.

Surely here more questions could arrive, "how to close app then". But if we don't want invest too much effort for that, then could ESC key press be our savior. 

So if user goes that minimal mode, it would be his/hers deliberate choice.
